<#
.SYNOPSIS
  Point the "m3-node" SSH alias at whichever M3 compute node your job is on.

.DESCRIPTION
  Run this LOCALLY (Windows) after starting a job with scripts/m3_session.sh.
  It asks the login node which host your job landed on and rewrites
  ~/.ssh/m3_node.conf, so VS Code Remote-SSH can always connect to the saved
  host "m3-node" instead of you retyping a new node name every session.

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File scripts\m3_connect.ps1
#>

$ErrorActionPreference = 'Stop'

Write-Host "Asking m3 which node your job is on..."
# Single-quoted so $USER is expanded by the remote shell, not by PowerShell.
$raw = ssh m3 'squeue -u $USER -h -o "%T %N"'

if ($LASTEXITCODE -ne 0) {
    throw "Could not reach m3. Check that 'ssh m3' works and that the User in ~/.ssh/config is stay0060."
}

$node = $raw -split "`n" |
    ForEach-Object { $_.Trim() } |
    Where-Object { $_ -match '^RUNNING\s+(\S+)$' } |
    ForEach-Object { $Matches[1] } |
    Select-Object -First 1

if (-not $node) {
    Write-Host ""
    Write-Host "No RUNNING job found. Start one first:" -ForegroundColor Yellow
    Write-Host "  ssh m3"
    Write-Host "  bash /projects/hz18/stay0060/NeuroBOLT/scripts/m3_session.sh 8"
    if ($raw.Trim()) { Write-Host ""; Write-Host "Current queue:"; Write-Host $raw }
    exit 1
}

$confPath = Join-Path $HOME ".ssh\m3_node.conf"
@"
# Auto-generated by scripts/m3_connect.ps1 -- do not edit by hand.
Host m3-node
    HostName $node
"@ | Set-Content -Path $confPath -Encoding ascii

Write-Host ""
Write-Host "m3-node -> $node" -ForegroundColor Green
Write-Host "In VS Code: Ctrl+Shift+P -> 'Remote-SSH: Connect to Host' -> m3-node"
